/** Section labels & content presets per business category (hotel-style layout) */
export const LAYOUT = {
  hospitality: {
    offerings: "Menu & Services",
    offeringsDesc: "Signature selections crafted for discerning guests.",
    features: "Amenities",
    featuresTitle: "World-Class Amenities",
    spotlight: "Experience",
    spotlightTitle: "The Culinary Experience",
    widget: "reservation",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Premium Quality", "Finest ingredients & materials"],
      ["◇", "Expert Team", "Trained professional staff"],
      ["★", "Ambiance", "Refined atmosphere"],
      ["▲", "Fresh Daily", "Seasonal & local sourcing"],
      ["●", "Private Events", "Custom celebrations"],
      ["■", "Delivery", "Convenient service options"],
      ["✦", "Loyalty Program", "Rewards for regulars"],
      ["✈", "Catering", "Off-site events available"],
    ],
    formServiceLabel: "Service Type",
    heroWidget: true,
  },
  wellness: {
    offerings: "Treatments",
    offeringsDesc: "Personalized services for body, mind, and spirit.",
    features: "Benefits",
    featuresTitle: "Why Choose Us",
    spotlight: "Wellness",
    spotlightTitle: "Your Wellness Journey",
    widget: "appointment",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Licensed Experts", "Certified practitioners"],
      ["◇", "Organic Products", "Premium natural formulas"],
      ["★", "Private Suites", "Tranquil treatment rooms"],
      ["▲", "Custom Plans", "Tailored to your goals"],
      ["●", "Relaxation Lounge", "Pre & post treatment"],
      ["■", "Gift Cards", "Perfect for loved ones"],
      ["✦", "Membership", "Exclusive member perks"],
      ["✈", "Couples Packages", "Shared experiences"],
    ],
    formServiceLabel: "Treatment",
    heroWidget: true,
  },
  fitness: {
    offerings: "Programs",
    offeringsDesc: "Training paths designed for every fitness level.",
    features: "Facilities",
    featuresTitle: "World-Class Facilities",
    spotlight: "Training",
    spotlightTitle: "Train Smarter, Go Further",
    widget: "trial",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Modern Equipment", "Latest machines & free weights"],
      ["◇", "Group Classes", "HIIT, yoga, spin & more"],
      ["★", "Personal Training", "Certified coaches"],
      ["▲", "Recovery Zone", "Sauna & stretch area"],
      ["●", "24/7 Access", "Train on your schedule"],
      ["■", "Nutrition Bar", "Protein shakes & snacks"],
      ["✦", "Locker Rooms", "Premium amenities"],
      ["✈", "Childcare", "Family-friendly hours"],
    ],
    formServiceLabel: "Program",
    heroWidget: true,
  },
  medical: {
    offerings: "Services",
    offeringsDesc: "Comprehensive care with compassion and expertise.",
    features: "Care Standards",
    featuresTitle: "Patient-First Care",
    spotlight: "Care",
    spotlightTitle: "Your Health, Our Priority",
    widget: "appointment",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Board Certified", "Expert physicians"],
      ["◇", "Modern Facility", "State-of-the-art equipment"],
      ["★", "Same-Day Care", "Urgent appointments"],
      ["▲", "Insurance Accepted", "Major plans welcome"],
      ["●", "Telehealth", "Virtual consultations"],
      ["■", "Lab On-Site", "Fast results"],
      ["✦", "Family Care", "All ages welcome"],
      ["✈", "Follow-Up", "Continuity of care"],
    ],
    formServiceLabel: "Service",
    heroWidget: true,
  },
  professional: {
    offerings: "Expertise",
    offeringsDesc: "Trusted solutions for complex challenges.",
    features: "Why Us",
    featuresTitle: "Our Advantages",
    spotlight: "Approach",
    spotlightTitle: "How We Work With You",
    widget: "consult",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Licensed Experts", "Qualified professionals"],
      ["◇", "Confidential", "Discretion guaranteed"],
      ["★", "Proven Results", "Track record of success"],
      ["▲", "Personalized", "Tailored strategies"],
      ["●", "Responsive", "Timely communication"],
      ["■", "Transparent", "Clear pricing"],
      ["✦", "Full Service", "End-to-end support"],
      ["✈", "Consultation", "Free initial meeting"],
    ],
    formServiceLabel: "Service Area",
    heroWidget: true,
  },
  retail: {
    offerings: "Collection",
    offeringsDesc: "Curated products selected for quality and style.",
    features: "Store Benefits",
    featuresTitle: "The Shopping Experience",
    spotlight: "Highlights",
    spotlightTitle: "Featured This Season",
    widget: "visit",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Curated Selection", "Hand-picked inventory"],
      ["◇", "Expert Advice", "Knowledgeable staff"],
      ["★", "Easy Returns", "Hassle-free policy"],
      ["▲", "Gift Wrapping", "Complimentary service"],
      ["●", "Loyalty Rewards", "Earn on every purchase"],
      ["■", "Online Orders", "Ship or pickup"],
      ["✦", "Private Shopping", "By appointment"],
      ["✈", "New Arrivals", "Weekly fresh stock"],
    ],
    formServiceLabel: "Interest",
    heroWidget: false,
  },
  trade: {
    offerings: "Services",
    offeringsDesc: "Professional solutions you can count on.",
    features: "Guarantees",
    featuresTitle: "Our Promise",
    spotlight: "Process",
    spotlightTitle: "How We Deliver",
    widget: "quote",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Licensed & Insured", "Fully certified"],
      ["◇", "Free Estimates", "No obligation quotes"],
      ["★", "On-Time", "Reliable scheduling"],
      ["▲", "Quality Work", "Satisfaction guaranteed"],
      ["●", "24/7 Emergency", "When you need us"],
      ["■", "Fair Pricing", "Transparent rates"],
      ["✦", "Warranty", "Work guaranteed"],
      ["✈", "Local Team", "Community trusted"],
    ],
    formServiceLabel: "Service Needed",
    heroWidget: true,
  },
  education: {
    offerings: "Programs",
    offeringsDesc: "Learning paths that deliver real results.",
    features: "Campus",
    featuresTitle: "Why Study With Us",
    spotlight: "Learning",
    spotlightTitle: "Our Teaching Philosophy",
    widget: "enroll",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Expert Faculty", "Industry professionals"],
      ["◇", "Small Classes", "Personal attention"],
      ["★", "Flexible Schedule", "Evening & weekend"],
      ["▲", "Career Support", "Job placement help"],
      ["●", "Modern Campus", "Equipped classrooms"],
      ["■", "Online Options", "Hybrid learning"],
      ["✦", "Scholarships", "Financial aid available"],
      ["✈", "Certification", "Recognized credentials"],
    ],
    formServiceLabel: "Program",
    heroWidget: true,
  },
  automotive: {
    offerings: "Services",
    offeringsDesc: "Expert automotive care and premium inventory.",
    features: "Standards",
    featuresTitle: "Why Drivers Trust Us",
    spotlight: "Service",
    spotlightTitle: "Expert Automotive Care",
    widget: "service",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Certified Techs", "ASE certified team"],
      ["◇", "Genuine Parts", "OEM quality"],
      ["★", "Warranty", "Work guaranteed"],
      ["▲", "Loaner Cars", "While we service"],
      ["●", "Free Inspection", "With every visit"],
      ["■", "Fair Pricing", "Upfront estimates"],
      ["✦", "Express Service", "Quick oil changes"],
      ["✈", "Detailing", "Showroom finish"],
    ],
    formServiceLabel: "Service Type",
    heroWidget: true,
  },
  events: {
    offerings: "Packages",
    offeringsDesc: "Memorable experiences, flawlessly executed.",
    features: "Includes",
    featuresTitle: "What's Included",
    spotlight: "Portfolio",
    spotlightTitle: "Signature Events",
    widget: "plan",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Full Planning", "End-to-end management"],
      ["◇", "Creative Team", "Design & styling"],
      ["★", "Vendor Network", "Trusted partners"],
      ["▲", "Day-Of Coordination", "Flawless execution"],
      ["●", "Custom Packages", "Tailored to budget"],
      ["■", "Photography", "Capture every moment"],
      ["✦", "Catering Options", "Curated menus"],
      ["✈", "Destination Events", "Travel weddings"],
    ],
    formServiceLabel: "Event Type",
    heroWidget: true,
  },
  pet: {
    offerings: "Services",
    offeringsDesc: "Loving care for your furry family members.",
    features: "Care",
    featuresTitle: "Our Pet Care Promise",
    spotlight: "Care",
    spotlightTitle: "A Home Away From Home",
    widget: "book",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Loving Staff", "Passionate caregivers"],
      ["◇", "Safe Environment", "Secure facilities"],
      ["★", "Daily Updates", "Photo reports"],
      ["▲", "Vet On Call", "Health monitoring"],
      ["●", "Play Groups", "Socialization"],
      ["■", "Grooming", "Full spa services"],
      ["✦", "Overnight Care", "24hr supervision"],
      ["✈", "Pickup Service", "Convenient transport"],
    ],
    formServiceLabel: "Service",
    heroWidget: true,
  },
  travel: {
    offerings: "Packages",
    offeringsDesc: "Curated journeys to the world's finest destinations.",
    features: "Benefits",
    featuresTitle: "Travel With Confidence",
    spotlight: "Destinations",
    spotlightTitle: "Explore the World",
    widget: "trip",
    nav: ["offerings", "features", "spotlight", "gallery"],
    featuresList: [
      ["◆", "Best Price", "Price match guarantee"],
      ["◇", "24/7 Support", "Always reachable"],
      ["★", "Expert Guides", "Local knowledge"],
      ["▲", "Custom Itineraries", "Tailored trips"],
      ["●", "Travel Insurance", "Peace of mind"],
      ["■", "Group Tours", "Small groups"],
      ["✦", "Luxury Options", "Premium upgrades"],
      ["✈", "Visa Assistance", "Documentation help"],
    ],
    formServiceLabel: "Destination",
    heroWidget: true,
  },
};

export const AMENITY_ICONS = {
  hospitality: ["pool", "spa", "gym", "wine"],
  wellness: ["spa", "wellness", "massage", "spa"],
  fitness: ["gym", "gym", "spa", "wellness"],
  medical: ["medical", "wellness", "spa", "medical"],
  professional: ["legal", "consulting", "finance", "insurance"],
  retail: ["fashion", "jewelry", "electronics", "furniture"],
  trade: ["construction", "electric", "plumbing", "cleaning"],
  education: ["coaching", "music", "language", "preschool"],
  automotive: ["dealership", "repair", "carwash", "dealership"],
  events: ["wedding", "photo", "dj", "events-food"],
  pet: ["petgroom", "vet", "petboard", "petgroom"],
  travel: ["travel", "tour", "rental", "travel"],
};

export const AMENITY_LABELS = {
  pool: "Infinity Pool", spa: "Wellness Spa", gym: "Fitness Club", wine: "Fine Dining",
  wellness: "Holistic Care", massage: "Massage Therapy", medical: "Clinical Care",
  legal: "Legal Expertise", consulting: "Strategy", finance: "Wealth", insurance: "Protection",
  fashion: "Boutique", jewelry: "Fine Jewelry", electronics: "Tech", furniture: "Living",
  construction: "Build", electric: "Electrical", plumbing: "Plumbing", cleaning: "Cleaning",
  coaching: "Academic", music: "Arts", language: "Languages", preschool: "Early Learning",
  dealership: "Showroom", repair: "Service", carwash: "Detailing",
  wedding: "Weddings", photo: "Photography", dj: "Entertainment", "events-food": "Catering",
  petgroom: "Grooming", vet: "Veterinary", petboard: "Boarding",
  travel: "Global Travel", tour: "Adventures", rental: "Rentals",
};

export const TESTIMONIALS = [
  { quote: "An absolutely exceptional experience. Professional, attentive, and truly premium in every detail.", name: "Sarah Mitchell", loc: "New York, USA", img: "photo-1494790108377-be9c29b29330" },
  { quote: "Exceeded every expectation. The quality and service are unmatched — we will definitely return.", name: "James Whitfield", loc: "London, UK", img: "photo-1507003211169-0a1dd7228f2d" },
  { quote: "I've tried many places, but nothing compares. Attention to detail makes all the difference.", name: "Elena Rodriguez", loc: "Barcelona, Spain", img: "photo-1438761681033-6461ffad8d80" },
  { quote: "Perfect for our needs. Impeccable service, outstanding results, and a team that truly cares.", name: "David Chen", loc: "Singapore", img: "photo-1472099645785-5658abf4ff4e" },
];

export const GALLERY_IDS = [
  "photo-1566073771259-6a8506099945",
  "photo-1542314831-068cd1dbccff",
  "photo-1582719478250-c89cae4dc85b",
  "photo-1559339352-11d035aa65de",
  "photo-1464366400600-7168b8af9bc3",
  "photo-1520250497591-112f2f40a3f4",
];

export function enrichBusiness(b) {
  const layout = LAYOUT[b.category] || LAYOUT.professional;
  const items = b.items.map((row) => {
    const [title, price, desc] = row.split("|");
    return { title, price, desc };
  });
  while (items.length < 4) {
    const extra = items[items.length - 1];
    items.push({ ...extra, title: extra.title + " Plus" });
  }
  const formatPrice = (p) => (/^[\$£€]|\d/.test(p) ? p : "Contact us");
  const priceLabel = (p) => {
    const f = formatPrice(p);
    return f === "Contact us" ? f : (f.startsWith("From") ? f : `From ${f}`);
  };
  const tags = [["Premium", "Expert", "Quality", "Care"], ["Pro", "Certified", "Trusted", "Fast"], ["Luxury", "Custom", "Support", "24/7"]];
  const tagSet = tags[b.slug.length % 3];
  return {
    ...b,
    layout,
    offerings: items.slice(0, 4).map((it, i) => ({
      ...it,
      price: formatPrice(it.price),
      image: `https://images.unsplash.com/${b.hero}?w=600&q=80&sig=${i}`,
      tags: tagSet,
      long: it.desc + " Designed for clients who expect the very best.",
    })),
    stats: [
      { val: b.stat1, label: b.stat1l, num: parseFloat(b.stat1.replace(/[^0-9.]/g, "")) || null },
      { val: b.stat2, label: b.stat2l, num: parseFloat(b.stat2.replace(/[^0-9.]/g, "")) || null },
      { val: b.stat3, label: b.stat3l, num: parseFloat(b.stat3) || 4.9 },
      { val: "24", label: "Hour Support", num: 24 },
    ],
    packages: [
      { title: b.offer, desc: b.offerDesc, price: priceLabel(items[0]?.price || ""), badge: "Featured", img: b.hero },
      { title: items[1]?.title || "Standard Package", desc: items[1]?.desc || "Our popular choice.", price: priceLabel(items[1]?.price || ""), img: b.hero },
      { title: items[2]?.title || "Premium Package", desc: items[2]?.desc || "The complete experience.", price: priceLabel(items[2]?.price || ""), img: b.hero },
    ],
    amenityIcons: (AMENITY_ICONS[b.category] || AMENITY_ICONS.professional).map((icon, i) => ({
      icon,
      label: AMENITY_LABELS[icon] || "Service " + (i + 1),
    })),
    showcase3d: items.slice(0, 3).map((it, i) => ({
      title: it.title,
      desc: it.desc,
      price: priceLabel(it.price),
      image: `https://images.unsplash.com/${b.hero}?w=1400&q=85&sig=${i + 10}`,
    })),
  };
}
